#include QMK_KEYBOARD_H

enum layer_names {
    _BASE,
    _GAME,
    _NAV,
    _NUM,
    _FUN
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    /* Keymap 0: Basic layer
    *
    * ┌-----┬-----┬-----┬-----┬-----┬-----┬-----┐    ┌-----┬-----┬-----┬-----┬-----┬-----┬----------┐
    * │     │     │     │     │     │     │     │    │     │     │     │     │     │     │          │
    * ├-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┘ ┌--┴-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬-------┤
    * │        │  Q  │  W  │  E  │  R  │  T  │    │  Y  │  U  │  I  │  O  │  P  │     │     │       │
    * ├--------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴-------┤
    * │         │  A  │  S  │  D  │  F  │  G  │    │  H  │  J  │  K  │  L  │  I  │     │            │
    * ├---------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬-----┬-----┤
    * │          │  Z  │  X  │  C  │  V  │  B  │    │  N  │  M  │  ,  │  .  │  /  │     │     │     │
    * ├------┬---┴-┬---┴--┬--┴-----┴----┬┴----┬┘   ┌┴-----┴-----┴--┬--┴----┬┴-----┼-----┼-----┼-----┤
    * │      │     │      │     Space   │     │    │      Ent      │       │      │     │     │     │
    * └------┴-----┴------┴-------------┴-----┘    └---------------┴-------┴------┴-----┴-----┴-----┘
    */
	[_BASE] = LAYOUT(
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_F24,
        KC_Q,     KC_W,     KC_E,     KC_R,     KC_T,     KC_NO,     KC_NO,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_NO,     KC_NO,
        KC_A,     LALT_T(KC_S),     LCTL_T(KC_D),     LSFT_T(KC_F),     KC_G,KC_NO,     KC_NO,          KC_H,     RSFT_T(KC_J),     RCTL_T(KC_K),     RALT_T(KC_L),     RGUI_T(KC_SCLN),     KC_NO,
        KC_Z,     KC_X,     KC_C,     KC_V,     KC_B,KC_NO,     KC_NO,          KC_N,     KC_M,     KC_COMM,     KC_DOT,     KC_SLSH,     KC_NO,     KC_NO,
        KC_NO,     KC_NO,     KC_NO,     LT(2,KC_ESC),     KC_SPC,     OSL(3),     KC_BSPC,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    /* Keymap 0: Gaming layer
    *
    * ┌-----┬-----┬-----┬-----┬-----┬-----┬-----┐    ┌-----┬-----┬-----┬-----┬-----┬-----┬----------┐
    * │     │     │     │     │     │     │     │    │     │     │     │     │     │     │          │
    * ├-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┘ ┌--┴-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬-------┤
    * │        │ Sft │  Q  │  W  │  E  │  T  │    │     │     │     │     │     │     │     │       │
    * ├--------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴-------┤
    * │         │ Tab │  A  │  S  │  D  │  F  │    │     │     │     │     │     │     │            │
    * ├---------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬-----┬-----┤
    * │          │ Ctl │ Alt │     │  R  │  G  │    │     │     │     │     │     │     │     │     │
    * ├------┬---┴-┬---┴--┬--┴-----┴----┬┴----┬┘   ┌┴-----┴-----┴--┬--┴----┬┴-----┼-----┼-----┼-----┤
    * │      │     │      │             │     │    │               │       │      │     │     │     │
    * └------┴-----┴------┴-------------┴-----┘    └---------------┴-------┴------┴-----┴-----┴-----┘
    */
	[_GAME] = LAYOUT(
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_F24,
        KC_LSFT,     KC_Q,     KC_W,     KC_E,     KC_T,     KC_NO,     KC_NO,     KC_Y,     KC_U,     KC_I,     KC_O,     KC_P,     KC_NO,     KC_NO,
        KC_LALT,     KC_A,     KC_S,     KC_D,     KC_F,     KC_NO,     KC_NO,     KC_H,     KC_J,     KC_K,     KC_L,     KC_SCLN,     KC_NO,
        KC_LCTL,     KC_TAB,     KC_NO,     KC_R,     KC_G,     KC_NO,     KC_NO,     KC_LBRC,     KC_QUOT,     KC_RBRC,     KC_MINS,     KC_EQL,     KC_NO,     KC_NO,
        KC_NO,     KC_NO,     KC_NO,     LT(2,KC_BSPC),     KC_SPC,     KC_ENT,     OSL(3),     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    /* Keymap 0: Nav layer
    *
    * ┌-----┬-----┬-----┬-----┬-----┬-----┬-----┐    ┌-----┬-----┬-----┬-----┬-----┬-----┬----------┐
    * │     │     │     │     │     │     │     │    │     │     │     │     │     │     │          │
    * ├-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┘ ┌--┴-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬-------┤
    * │        │     │     │     │     │     │    │     │     │     │     │     │     │     │       │
    * ├--------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴-------┤
    * │         │     │     │     │     │     │    │     │     │     │     │     │     │            │
    * ├---------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬-----┬-----┤
    * │          │     │     │     │     │     │    │     │     │     │     │     │     │     │     │
    * ├------┬---┴-┬---┴--┬--┴-----┴----┬┴----┬┘   ┌┴-----┴-----┴--┬--┴----┬┴-----┼-----┼-----┼-----┤
    * │      │     │      │             │     │    │               │       │      │     │     │     │
    * └------┴-----┴------┴-------------┴-----┘    └---------------┴-------┴------┴-----┴-----┴-----┘
    */
	[_NAV] = LAYOUT(
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_F24,
        LGUI(KC_TAB),     LCTL(KC_TAB),     KC_NO,     LCTL(KC_T),     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_LSFT,     KC_LCTL,     KC_LALT,     KC_LGUI,     KC_NO,     KC_NO,
        KC_TAB,     KC_LEFT,     KC_UP,     KC_RGHT,     LCTL(LSFT(KC_R)),     KC_NO,     KC_NO,     KC_NO,     KC_HOME,     KC_PGUP,     KC_END,     KC_NO,     KC_NO,
        KC_NO,     LCTL(LSFT(KC_TAB)),     KC_DOWN,     LCTL(KC_W),     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_PGDN,     DF(0),     DF(1),     KC_NO,     KC_NO,
        KC_NO,     KC_NO,     KC_NO,     KC_TRNS,     KC_SPC,     KC_ENT,     KC_BSPC,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    /* Keymap 0: Number layer
    *
    * ┌-----┬-----┬-----┬-----┬-----┬-----┬-----┐    ┌-----┬-----┬-----┬-----┬-----┬-----┬----------┐
    * │     │     │     │     │     │     │     │    │     │     │     │     │     │     │          │
    * ├-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┘ ┌--┴-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬-------┤
    * │        │     │     │     │     │     │    │     │     │     │     │     │     │     │       │
    * ├--------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴-------┤
    * │         │     │     │     │     │     │    │     │     │     │     │     │     │            │
    * ├---------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬-----┬-----┤
    * │          │     │     │     │     │     │    │     │     │     │     │     │     │     │     │
    * ├------┬---┴-┬---┴--┬--┴-----┴----┬┴----┬┘   ┌┴-----┴-----┴--┬--┴----┬┴-----┼-----┼-----┼-----┤
    * │      │     │      │             │     │    │               │       │      │     │     │     │
    * └------┴-----┴------┴-------------┴-----┘    └---------------┴-------┴------┴-----┴-----┴-----┘
    */
	[_NUM] = LAYOUT(
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_F24,
        KC_TILD,     KC_7,     KC_8,     KC_9,     KC_MINS,     KC_NO,     KC_NO,     KC_LPRN,     KC_QUOT,     KC_DQUO,     KC_PSLS,     KC_RPRN,     KC_NO,     KC_NO,
        KC_GRV,     KC_4,     KC_5,     LSFT_T(KC_6),     KC_EQL,     KC_NO,     KC_NO,     KC_SCLN,     RSFT_T(KC_DOT),     KC_COMM,     KC_QUES,     KC_EXLM,     KC_NO,
        KC_0,     KC_1,     KC_2,     KC_3,     KC_BSLS,     KC_NO,     KC_NO,     KC_LBRC,     KC_AT,     KC_AMPR,     KC_DLR,     KC_RBRC,     KC_NO,     KC_NO,
        KC_NO,     KC_NO,     KC_NO,     KC_ESC,     KC_SPC,     KC_ENT,     OSL(4),     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    /* Keymap 0: Function layer
    *
    * ┌-----┬-----┬-----┬-----┬-----┬-----┬-----┐    ┌-----┬-----┬-----┬-----┬-----┬-----┬----------┐
    * │     │     │     │     │     │     │     │    │     │     │     │     │     │     │          │
    * ├-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┘ ┌--┴-----┴--┬--┴--┬--┴--┬--┴--┬--┴--┬--┴--┬-------┤
    * │        │     │     │     │     │     │    │     │     │     │     │     │     │     │       │
    * ├--------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴-------┤
    * │         │     │     │     │     │     │    │     │     │     │     │     │     │            │
    * ├---------┴┬----┴┬----┴┬----┴┬----┴┬----┴┐   └┬----┴┬----┴┬----┴┬----┴┬----┴┬----┴┬-----┬-----┤
    * │          │     │     │     │     │     │    │     │     │     │     │     │     │     │     │
    * ├------┬---┴-┬---┴--┬--┴-----┴----┬┴----┬┘   ┌┴-----┴-----┴--┬--┴----┬┴-----┼-----┼-----┼-----┤
    * │      │     │      │             │     │    │               │       │      │     │     │     │
    * └------┴-----┴------┴-------------┴-----┘    └---------------┴-------┴------┴-----┴-----┴-----┘
    */
	[_FUN] = LAYOUT(
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_F24,
        KC_F12,     KC_F7,     KC_F8,     KC_F9,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_INS,     KC_DEL,     KC_NO,     KC_NO,     KC_NO,     KC_NO,
        KC_F11,     KC_F4,     KC_F5,     KC_F6,     KC_CAPS,     KC_NO,     KC_NO,     KC_NO,     KC_LSFT,     KC_LCTL,     KC_LALT,     KC_LGUI,     KC_NO,
        KC_F10,     KC_F1,     KC_F2,     KC_F3,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,
        KC_NO,     KC_NO,     KC_NO,     KC_ESC,     KC_SPC,     KC_ENT,     KC_BSPC,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    )
};
